name: Pulblish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get diff from CHANGELOG
        run: |
          BEFORE=`git describe --tags v${GITHUB_REF#refs/*/v}^^`
          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          git diff -u $BEFORE CHANGELOG.md | grep ^+ | grep -v ^+++ | sed s/^+// >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          body: ${{ env.CHANGELOG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    
      - name: Create or switch to release branch
        run: |
          git checkout -B release

      - name: Copy files from tag
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          git checkout $TAG_NAME -- .
    
      - name: Commit changes
        run: |
          git add -A
          git commit -m "Update release branch to $TAG_NAME"
    
      - name: Push to release branch
        run: |
          git push origin release --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4 
      - name: Publish to PyPI
        run: |
          PDM_BUILD_SCM_VERSION=${{ env.RELEASE_VERSION }} pdm publish