name: Pulblish to PyPI

on:
  release: 
    types: [released]
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: "Set env"
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
            git tag ${{ github.event.inputs.version }}
          else
            echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          fi
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Create or switch to release branch
        run: |
          git checkout -B release
      - name: Copy files from tag
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          git checkout $TAG_NAME -- .
      - name: Commit changes
        run: |
          git add -A
          git commit -m "Update release branch to $TAG_NAME"
      - name: Push to release branch
        run: |
          git push origin release --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: echo version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4 
      - name: Publish to PyPI
        run: |
          PDM_BUILD_SCM_VERSION=${{ env.RELEASE_VERSION }} pdm publish